###############################################################################
##
## Talon Configurations for Third Coast Drive
##
###############################################################################

[[TALON]]
  name = "drive"
  mode = "Voltage"
  setpointMax    = 12.0
  currentLimit   = 50
  [TALON.encoder]
    device = "QuadEncoder"
    reversed = false

[[TALON]]
  name = "azimuth"
  mode = "Position"
  setpointMax     = 4095.0
  brakeInNeutral = false
  outputReversed = false
  forward_output_voltage_peak =  6.0
  reverse_output_voltage_peak = -6.0
  # NOTE: you must provide azimuth Talon closed-loop tuning parameters below
  pGain =   0.0
  iGain =   0.0
  dGain =   0.0
  fGain =   0.0
  iZone =   0
  [TALON.encoder]
    device  = "CtreMagEncoder_Relative"
    reversed = false
