###############################################################################
##
## Talon Configurations
##
###############################################################################

## feedback device
###############################################################################
# quad         = 0
# analog pot   = 2
# analog enc   = 3
# enc rising   = 4
# enc falling  = 5
# mag relative = 6
# mag absolute = 7
# pulse width  = 8

## neutral mode
###############################################################################
# jumper = 0
# brake  = 1
# coast  = 2

## limit mode
###############################################################################
# only use switches for limits             = 0
# use both switches and soft limits        = 1
# disable switches and disable soft limits = 2

[[TALON]]
# Each talon configuration name needs to be globally unique.
name = "drive_teleop"

# Select a control mode from the following list. Note this is case-sensative.
# If not specified, defaults to Voltage.
#  - Current
#  - Disabled
#  - Follower
#  - MotionMagic
#  - MotionProfile
#  - PercentVbus
#  - Position
#  - Speed
#  - Voltage
mode = "Voltage"

# Max input or throttle will scale to this absolute value. Units are the
# same at the setpoint, i.e. volts, ticks, etc... Applies to all modes.
setpoint_max      = 12.0 # max volts

# Select feedback device from the following list. Note this is case-sensative.
# If not specified, defaults to QuadEncoder. Applies to all modes.
#  - AnalogEncoder
#  - AnalogPot
#  - CtreMagEncoder_Absolute
#  - CtreMagEncoder_Relative
#  - EncFalling
#  - EncRising
#  - PulseWidth
#  - QuadEncoder
feedback_device = "CtreMagEncoder_Relative"

# Configure how many codes per revolution are generated by this encoder. See
# Talon software manual section 7.2. If not specified, Talon will use native
# units.  Applies to all modes.
ticks_per_revolution = 4096

# Set to true to brake during neutral, false to coast during neutral. If not
# specified, defaults to true. Applies to all modes.
brake_in_neutral = true

# Limit switches are normally-open, normally-closed, or disabled. If not
# specified, defaults to disabled. Applies to all modes.
#  - NormallyOpen
#  - NormallyClosed
#  - Disabled
forward_limit_switch = "NormallyOpen"
reverse_limit_switch = "Disabled"

# Soft limits are set if the following options are present. Units are the
# same at the setpoint, i.e. volts, ticks. Applies to all modes.
forward_soft_limit = 10000.0
reverse_soft_limit = 12000.0

# Set to true to reverse the encoder sensing direction to be in-phase with
# motor output. If not specified, defaults to false. Applies to all modes.
encoder_reversed  = false

# Set to true to reverse motor output. If not specified, defaults to false.
# Applies to all modes.
output_reversed   = false

# The Velocity Measurement Sample Period is selected from a fixed list of
# pre-supported sampling periods [1, 5, 10, 20, 25, 50, 100] milliseconds (see
# Talon software manual section 7.8). If not specified, defaults to 100 ms.
velocity_measurement_period = 100

#  The Velocity Measurement Rolling Average Window is selected from a fixed list
#  of pre-supported sample counts: [1, 2, 4, 8, 16, 32, 64]. If an alternative
#  value is specified, it is rounded down to the nearest supported value. If not
#  specified, defaults to 64.
velocity_measurement_window = 64

# Limit current to specified maximum. A value of zero will disable current
# limit.  Applies to all modes.
current_limit     = 50

# Set a maximum output voltage ramp rate, in volts/sec. A value at or near zero
# will disable ramping (see Talon software manual section 6.4).  Applies to all
# modes.
voltage_ramp_rate = 0.0

[[TALON]]
name = "azimuth_teleop"
mode = "Position"

# Set the maximum voltage that the Talon will ever output. This can be used to
# limit the maximum output voltage (positive or negative) in closed-loop modes
# so that motors which cannot withstand full bus voltage can be used safely. If
# not specified, defaults to no limit.
output_voltage_max = 12.0

# Output voltage will be limited to this value. Applies to closed-loop modes.
forward_output_voltage_peak = 5.0
reverse_output_voltage_peak = 5.0

# Output magnitude between zero and this value is set to this value. Applies to
# closed-loop modes.
forward_output_voltage_nominal = 0.0
reverse_output_voltage_nominal = 0.0
