##
## Third Coast Defaults
##

[THIRDCOAST.SWERVE]
  length = 1.0
  width = 1.0

[THIRDCOAST.WHEEL]
  ticksPerRevolution = 4096
  azimuthConfig = "azimuth"
  driveConfig = "drive"

[THIRDCOAST.TALON]
  timeout = 10

[[TALON]]
  name = "drive"
  mode = "PercentOutput"
  setpointMax    = 12.0
  currentLimit   = 50
  [TALON.encoder]
    device = "CTRE_MagEncoder_Relative"
    reversed = false

[[TALON]]
  name = "azimuth"
  mode = "Position"
  setpointMax     = 4095
  brakeInNeutral = false
  forwardOutputVoltagePeak =  6.0
  reverseOutputVoltagePeak = -6.0
  # NOTE: you must provide azimuth Talon closed-loop tuning parameters below
  pGain =   0.0
  iGain =   0.0
  dGain =   0.0
  fGain =   0.0
  iZone =   0
  [TALON.encoder]
    device  = "CTRE_MagEncoder_Relative"
    reversed = false
